services:
  saber_unerg_prod:
    build: .
    ports:
      - "6100:80"
    volumes:
      - .:/var/www/html
      - ./ojs-files:/var/www/html/files
      - ./ojs-files:/var/www/files   
    environment:
      DB_HOST: 162.212.153.19
      DB_USER: saber
      DB_PASSWORD: DirInfo01
      DB_NAME: saber_unerg
      DB_PORT: 2955
