services:
  saber_unerg_prod:
    build: .
    ports:
      - "6100:80"
    volumes:
      - .:/var/www/html
      - ./ojs-files:/var/www/html/files
      - ./ojs-files:/var/www/files   
    environment:
      DB_HOST: mariadb_container
      DB_USER: dir_informatica
      DB_PASSWORD: dir_informatica
      DB_NAME: saber_unerg